[package]
name = "subpixel-edge"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.*"
imageproc = { version = "0.25.*", features = ["rayon"] }
log = "0.4.27"
rayon = "1.10.0"

[dev-dependencies]
env_logger = "0.11.8"
